### ISSUE TITLE
unknown operand

### ISSUE THREAD

**Issue by Peelige** [h0me5k1n/iptv-strmmaker#1]
Hi there,

This script looks perfect for what I need, only it's giving an error against the m3u :

bash: tvg-id="": unknown operand
bash: tvg-id="": unknown operand
bash: tvg-id="": unknown operand
ERROR REPORTED

Any ideas? the temp.m3u is in this form :

#EXTINF:-1 tvg-id="" tvg-name="Police Story" group-title="" tvg-logo="",Police Story
http://url/75723.mp4
#EXTINF:-1 tvg-id="" tvg-name="The Money Pit" group-title="" tvg-logo="",The Money Pit
http://url/89419.mp4

**Comment by h0me5k1n** [comment]
Are you able to share more of the URL... The script looks for the word "Movies" or "movies" in order to match to the entry being a tv or movie entry. I'll look to create an m3u file for testing then.

Please don't share the full host name or any sensitive data.

**Comment by Peelige** [comment]
Hi @h0me5k1n , thanks for the reply.  

Sure, i've linked a sample here so you can see more;

[https://www.dropbox.com/s/djfgiteq0y0fd5b/temp.m3u?dl=1](https://www.dropbox.com/s/djfgiteq0y0fd5b/temp.m3u?dl=1)

**Comment by Peelige** [comment]
Hi @h0me5k1n, did you manage to take a look at this yet?  Need anything more from me?

Thanks in advance :)

**Comment by h0me5k1n** [comment]
it works for me with your file... I added a line with the following text in a file called "vodselection-movies" in the script folder and it created an strm file as expected:
.*Pit.*
(.[asterisk]Pit.[asterisk])

I had to add a line with the following text in a file called "vodselection-tv" for the tv series to be handled:
Latest TV Shows

What do you have in your "vodselection" files? Any special characters... or quote marks??

I've updated the script today to handle when old items are removed - I don't think I've made any changes to the sections that you might be having issues with but try the new version.

**Comment by h0me5k1n** [comment]
Can you let me K n ow if you still have an issue @Peelige?

**Comment by h0me5k1n** [comment]
Closed without resolution.
No further information provided.
